extends Node

# This script is a workaround to force Godot's exporter to include
# dynamically loaded resources. It preloads all card and tile images
# so they are guaranteed to be included in the exported project.

# Card Illustrations
const card_abundance = preload("res://assets/card_art/illustrations/abundance.png")
const card_blessed_ore = preload("res://assets/card_art/illustrations/blessed_ore.png")
const card_building = preload("res://assets/card_art/illustrations/building.png")
const card_call_of_the_faithful = preload("res://assets/card_art/illustrations/call_of_the_faithful.png")
const card_cataclysm = preload("res://assets/card_art/illustrations/cataclysm.png")
const card_citizen = preload("res://assets/card_art/illustrations/citizen.png")
const card_deitys_favor = preload("res://assets/card_art/illustrations/deity's_favor.png")
const card_desert_winds = preload("res://assets/card_art/illustrations/desert_winds.png")
const card_divine_birth = preload("res://assets/card_art/illustrations/divine_birth.png")
const card_divine_curse = preload("res://assets/card_art/illustrations/divine_curse.png")
const card_divine_harvest = preload("res://assets/card_art/illustrations/divine_harvest.png")
const card_divine_healing = preload("res://assets/card_art/illustrations/divine_healing.png")
const card_divine_prosperity = preload("res://assets/card_art/illustrations/divine_prosperity.png")
const card_divine_shield = preload("res://assets/card_art/illustrations/divine_shield.png")
const card_divine_terraforming = preload("res://assets/card_art/illustrations/divine_terraforming.png")
const card_divine_wrath = preload("res://assets/card_art/illustrations/divine_wrath.png")
const card_drought = preload("res://assets/card_art/illustrations/drought.png")
const card_earthquake = preload("res://assets/card_art/illustrations/earthquake.png")
const card_eternal_winter = preload("res://assets/card_art/illustrations/eternal_winter.png")
const card_famine = preload("res://assets/card_art/illustrations/famine.png")
const card_fortify = preload("res://assets/card_art/illustrations/fortify.png")
const card_iron_blessing = preload("res://assets/card_art/illustrations/iron_blessing.png")
const card_lightning_strike = preload("res://assets/card_art/illustrations/lightning_strike.png")
const card_manna_from_heaven = preload("res://assets/card_art/illustrations/manna_from_heaven.png")
const card_mass_migration = preload("res://assets/card_art/illustrations/mass_migration.png")
const card_mass_teleport = preload("res://assets/card_art/illustrations/mass_teleport.png")
const card_meteor_shower = preload("res://assets/card_art/illustrations/meteor_shower.png")
const card_mineral_vein = preload("res://assets/card_art/illustrations/mineral_vein.png")
const card_mountains_rise = preload("res://assets/card_art/illustrations/mountain's_rise.png")
const card_oceans_blessing = preload("res://assets/card_art/illustrations/ocean's_blessing.png")
const card_plague = preload("res://assets/card_art/illustrations/plague.png")
const card_raise_army = preload("res://assets/card_art/illustrations/raise_army.png")
const card_sacred_grove = preload("res://assets/card_art/illustrations/sacred_grove.png")
const card_smite = preload("res://assets/card_art/illustrations/smite.png")
const card_spring_of_life = preload("res://assets/card_art/illustrations/spring_of_life.png")
const card_springs_gift = preload("res://assets/card_art/illustrations/spring's_gift.png")
const card_stone_gifts = preload("res://assets/card_art/illustrations/stone_gifts.png")
const card_summon_villagers = preload("res://assets/card_art/illustrations/summon_villagers.png")
const card_timber_blessing = preload("res://assets/card_art/illustrations/timber_blessing.png")
const card_timber_bounty = preload("res://assets/card_art/illustrations/timber_bounty.png")
const card_time_stop = preload("res://assets/card_art/illustrations/time_stop.png")
const card_verdant_growth = preload("res://assets/card_art/illustrations/verdant_growth.png")
const card_volcanic_fury = preload("res://assets/card_art/illustrations/volcanic_fury.png")
const card_warrior = preload("res://assets/card_art/illustrations/warrior.png")

# Tile Art (Original)
const tile_chasm = preload("res://assets/tile_art/chasm.png")
const tile_cold_water = preload("res://assets/tile_art/cold_water.png")
const tile_deep_sea = preload("res://assets/tile_art/deep_sea.png")
const tile_dry_grassland_river = preload("res://assets/tile_art/dry_grassland_river.png")
const tile_dry_grassland = preload("res://assets/tile_art/dry_grassland.png")
const tile_forest_river = preload("res://assets/tile_art/forest_river.png")
const tile_forest = preload("res://assets/tile_art/forest.png")
const tile_grass_river = preload("res://assets/tile_art/grass_river.png")
const tile_grass = preload("res://assets/tile_art/grass.png")
const tile_hills_river = preload("res://assets/tile_art/hills_river.png")
const tile_hills = preload("res://assets/tile_art/hills.png")
const tile_ice_water = preload("res://assets/tile_art/ice_water.png")
const tile_jungle_river = preload("res://assets/tile_art/jungle_river.png")
const tile_jungle = preload("res://assets/tile_art/jungle.png")
const tile_lava = preload("res://assets/tile_art/lava.png")
const tile_mountains_river = preload("res://assets/tile_art/mountains_river.png")
const tile_mountains = preload("res://assets/tile_art/mountains.png")
const tile_rocky_peak_river = preload("res://assets/tile_art/rocky_peak_river.png")
const tile_rocky_peak = preload("res://assets/tile_art/rocky_peak.png")
const tile_sand = preload("res://assets/tile_art/sand.png")
const tile_snow_peak_river = preload("res://assets/tile_art/snow_peak_river.png")
const tile_snow_peak = preload("res://assets/tile_art/snow_peak.png")
const tile_stone_river = preload("res://assets/tile_art/stone_river.png")
const tile_stone = preload("res://assets/tile_art/stone.png")
const tile_water = preload("res://assets/tile_art/water.png")

# Tile Art (Fantasy Bordered)
const tile_fb_chasm = preload("res://assets/tile_art/fantasy_bordered/chasm.png")
const tile_fb_cold_water = preload("res://assets/tile_art/fantasy_bordered/cold_water.png")
const tile_fb_deep_sea = preload("res://assets/tile_art/fantasy_bordered/deep_sea.png")
const tile_fb_dry_grassland = preload("res://assets/tile_art/fantasy_bordered/dry_grassland.png")
const tile_fb_forest = preload("res://assets/tile_art/fantasy_bordered/forest.png")
const tile_fb_grass = preload("res://assets/tile_art/fantasy_bordered/grass.png")
const tile_fb_hills = preload("res://assets/tile_art/fantasy_bordered/hills.png")
const tile_fb_ice_water = preload("res://assets/tile_art/fantasy_bordered/ice_water.png")
const tile_fb_jungle = preload("res://assets/tile_art/fantasy_bordered/jungle.png")
const tile_fb_lava = preload("res://assets/tile_art/fantasy_bordered/lava.png")
const tile_fb_mountains = preload("res://assets/tile_art/fantasy_bordered/mountains.png")
const tile_fb_rocky_peak = preload("res://assets/tile_art/fantasy_bordered/rocky_peak.png")
const tile_fb_sand = preload("res://assets/tile_art/fantasy_bordered/sand.png")
const tile_fb_snow_peak = preload("res://assets/tile_art/fantasy_bordered/snow_peak.png")
const tile_fb_stone = preload("res://assets/tile_art/fantasy_bordered/stone.png")
const tile_fb_water = preload("res://assets/tile_art/fantasy_bordered/water.png")

# Tile Art (Fantasy Borderless)
const tile_fbl_chasm = preload("res://assets/tile_art/fantasy_borderless/chasm.png")
const tile_fbl_cold_water = preload("res://assets/tile_art/fantasy_borderless/cold_water.png")
const tile_fbl_deep_sea = preload("res://assets/tile_art/fantasy_borderless/deep_sea.png")
const tile_fbl_dry_grassland = preload("res://assets/tile_art/fantasy_borderless/dry_grassland.png")
const tile_fbl_forest = preload("res://assets/tile_art/fantasy_borderless/forest.png")
const tile_fbl_grass = preload("res://assets/tile_art/fantasy_borderless/grass.png")
const tile_fbl_hills = preload("res://assets/tile_art/fantasy_borderless/hills.png")
const tile_fbl_ice_water = preload("res://assets/tile_art/fantasy_borderless/ice_water.png")
const tile_fbl_jungle = preload("res://assets/tile_art/fantasy_borderless/jungle.png")
const tile_fbl_lava = preload("res://assets/tile_art/fantasy_borderless/lava.png")
const tile_fbl_mountains = preload("res://assets/tile_art/fantasy_borderless/mountains.png")
const tile_fbl_rocky_peak = preload("res://assets/tile_art/fantasy_borderless/rocky_peak.png")
const tile_fbl_sand = preload("res://assets/tile_art/fantasy_borderless/sand.png")
const tile_fbl_snow_peak = preload("res://assets/tile_art/fantasy_borderless/snow_peak.png")
const tile_fbl_stone = preload("res://assets/tile_art/fantasy_borderless/stone.png")
const tile_fbl_water = preload("res://assets/tile_art/fantasy_borderless/water.png")